spring.application.name=demoReactor
logging.level.org.springframework.data.r2dbc=DEBUG
server.port=7071
# URL de conexion R2DBC para postgresql
#spring.r2dbc.url=r2dbc:postgresql://localhost/mesero2023v
#spring.r2dbc.username=postgres
#spring.r2dbc.password=123
# URL de conexion R2DBC para MySql
spring.r2dbc.url=r2dbc:mysql://localhost:3306/mesero2023v
spring.r2dbc.username=root
spring.r2dbc.password=root


###con docker
#spring.application.name=demoReactor
#server.port=7071
#spring.r2dbc.url=${SPRING_R2DBC_URL}
#spring.r2dbc.username=${SPRING_R2DBC_USERNAME}
#spring.r2dbc.password=${SPRING_R2DBC_PASSWORD}
